### ISSUE TITLE
建議事項

### ISSUE THREAD

**Issue by crablin** [omoa123/ShopSystem#1]
1. 把購物車變成一個模組物件(Module)
例如：有一個購物車模組，此模組有新增(Add)跟計算結果(Summary)的方法可使用
2. 運行 Console 時，是否可印出 1，2，3 各是什麼商品，對於輸入商品代碼，但是不知道商品是什麼
3. 當購物車變成一個模組物件時，是否可將邏輯跟單純的資料物件分開存放

**Comment by crablin** [comment]
1. 命名的問題：

- 列舉命名不能為中文名稱
- 命名的一致性，公開方法或參數請用大寫駝峰，私域方法請用小寫駝峰

延伸問題：另外，當如果後來要多一些商品品項時，程式的修改可能會過大

2. 思考購物車是否有效能問題？為何一定要記錄整個物件？

**Comment by crablin** [comment]
Product 自己產生 ProductList 不覺得怪嗎？
Product 是 Model 型別，儘量少在模組上有連線或產生資料的method
可以的話，修改一下架構

**Comment by omoa123** [comment]
code 已作對應修正
